# Generated by Django 5.1.2 on 2024-10-21 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Добавьте дату создания продукта', verbose_name='Дата создания продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Добавьте датe производства продукта', verbose_name='Дата производства продукта'),
        ),
    ]
